### ISSUE TITLE
Merge changes by @apires

### ISSUE THREAD

**Issue by levrik** [DerNivel/sinon-spy-react#5]
@apires I really like your changes in your fork (https://github.com/apires/sinon-spy-react). Could you create a pull request here?

**Comment by apires** [comment]
Of course! I haven't written anything production quality that uses my changes though, so my changes are not fully tested so watch out! :) Wasn't sure about submitting a pull request since I did change the API (renaming things) a bit.

**Comment by levrik** [comment]
I will merge and refactor it a bit. When I have time I will add unit tests to this project.

**Comment by levrik** [comment]
PR: #6
